include:
  - project: 'city-of-helsinki/kuva/ci-cd-config/ci-configuration'
    ref: v2
    file: '/.gitlab-ci-template.yml'

variables:
  SERVICE_PORT: 80

build-review:
  # These variables are available only for review env and are merged with the general variables defined above.
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'
    DOCKER_BUILD_ARG_REACT_APP_ENVIRONMENT: 'review'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: 'https://api.hel.fi/sso-test/'
    DOCKER_BUILD_ARG_REACT_APP_PROFILE_AUDIENCE: 'https://api.hel.fi/auth/helsinkiprofile'
    DOCKER_BUILD_ARG_REACT_APP_JASSARI_AUDIENCE: 'https://api.hel.fi/auth/jassariapi'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_CLIENT_ID: 'https://api.hel.fi/auth/jassari-admin-ui'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_SCOPE: 'openid $DOCKER_BUILD_ARG_REACT_APP_JASSARI_AUDIENCE $DOCKER_BUILD_ARG_REACT_APP_PROFILE_AUDIENCE'
    DOCKER_BUILD_ARG_REACT_APP_JASSARI_FEDERATION_GRAPHQL: 'https://jassari-federation.test.kuva.hel.ninja/'
    DOCKER_BUILD_ARG_REACT_APP_SENTRY_DSN: 'https://13e1b97fb11c4d10976a27675061c6c3@sentry.hel.ninja/60'
    DOCKER_BUILD_ARG_REACT_APP_BASE_URL: 'https://jassari-admin.test.kuva.hel.ninja/'
  only:
    refs:
      - external_pull_requests

build-staging:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
    DOCKER_BUILD_ARG_REACT_APP_ENVIRONMENT: 'staging'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: 'https://api.hel.fi/sso-test/'
    DOCKER_BUILD_ARG_REACT_APP_PROFILE_AUDIENCE: 'https://api.hel.fi/auth/helsinkiprofile'
    DOCKER_BUILD_ARG_REACT_APP_JASSARI_AUDIENCE: 'https://api.hel.fi/auth/jassariapi'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_CLIENT_ID: 'https://api.hel.fi/auth/jassari-admin-ui'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_SCOPE: 'openid $DOCKER_BUILD_ARG_REACT_APP_JASSARI_AUDIENCE $DOCKER_BUILD_ARG_REACT_APP_PROFILE_AUDIENCE'
    DOCKER_BUILD_ARG_REACT_APP_JASSARI_FEDERATION_GRAPHQL: 'https://jassari-federation.test.kuva.hel.ninja/'
    DOCKER_BUILD_ARG_REACT_APP_SENTRY_DSN: 'https://13e1b97fb11c4d10976a27675061c6c3@sentry.hel.ninja/60'
    DOCKER_BUILD_ARG_REACT_APP_BASE_URL: 'https://jassari-admin.test.kuva.hel.ninja/'
  only:
    refs:
      - develop

build-production:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-production'
    DOCKER_BUILD_ARG_REACT_APP_ENVIRONMENT: 'production'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: 'https://api.hel.fi/sso/'
    DOCKER_BUILD_ARG_REACT_APP_PROFILE_AUDIENCE: 'https://api.hel.fi/auth/helsinkiprofile'
    DOCKER_BUILD_ARG_REACT_APP_JASSARI_AUDIENCE: 'https://api.hel.fi/auth/jassariapi'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_CLIENT_ID: 'https://id.hel.fi/auth/clients/jassari-admin-prod'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_SCOPE: 'openid $DOCKER_BUILD_ARG_REACT_APP_JASSARI_AUDIENCE $DOCKER_BUILD_ARG_REACT_APP_PROFILE_AUDIENCE'
    DOCKER_BUILD_ARG_REACT_APP_JASSARI_FEDERATION_GRAPHQL: 'https://jassari-federation.prod.kuva.hel.ninja/'
    DOCKER_BUILD_ARG_REACT_APP_SENTRY_DSN: 'https://13e1b97fb11c4d10976a27675061c6c3@sentry.hel.ninja/60'
    DOCKER_BUILD_ARG_REACT_APP_BASE_URL: 'https://jassari-admin.hel.fi/'
  only:
    refs:
      - master
      # this regexp will match release-tags
      - /^release-.*$/

review:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'
    POSTGRES_ENABLED: 0

# This will enable staging ci-pipeline
staging:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
  only:
    refs:
      - develop

production:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-production'
