version: '3.7'

services:
  app:
    container_name: youth-membership-admin-ui
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3001'
