name: Build & Review
on: [pull_request]

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN_STAGING }}
  SERVICE_PORT: 80
  PROFILE_AUDIENCE: 'https://api.hel.fi/auth/helsinkiprofile'
  JASSARI_AUDIENCE: 'https://api.hel.fi/auth/jassariapi'
  K8S_REQUEST_CPU: 1m
  K8S_REQUEST_RAM: 10Mi
  K8S_LIMIT_CPU: 10m
  K8S_LIMIT_RAM: 20Mi

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: dump vars
        id: dump_vars 
        run: |
          echo "BROWSER_TESTING_USERNAME"
          echo ${{secrets.BROWSER_TESTING_USERNAME}} | sed 's/./& /g'
          echo "BROWSER_TESTING_USERNAME_NO_ACCESS"
          echo ${{secrets.BROWSER_TESTING_USERNAME_NO_ACCESS}} | sed 's/./& /g'
          echo "BROWSER_TESTING_PASSWORD"
          echo ${{secrets.BROWSER_TESTING_PASSWORD}} | sed 's/./& /g'
          echo "BROWSER_TESTING_EXISTING_USER_YOUTH_PROFILE_ID"
          echo ${{secrets.BROWSER_TESTING_EXISTING_USER_YOUTH_PROFILE_ID}} | sed 's/./& /g'
          echo "BROWSER_TESTING_EXISTING_USER_FIRST_NAME"
          echo ${{secrets.BROWSER_TESTING_EXISTING_USER_FIRST_NAME}} | sed 's/./& /g'
          echo "BROWSER_TESTING_EXISTING_USER_LAST_NAME"
          echo ${{secrets.BROWSER_TESTING_EXISTING_USER_LAST_NAME}} | sed 's/./& /g'

      - name: Build
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-review
          DOCKER_BUILD_ARG_REACT_APP_ENVIRONMENT: 'review'
          DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: 'https://tunnistamo.${{ env.BASE_DOMAIN }}/'
          DOCKER_BUILD_ARG_REACT_APP_PROFILE_AUDIENCE: ${{ env.PROFILE_AUDIENCE }}
          DOCKER_BUILD_ARG_REACT_APP_JASSARI_AUDIENCE: ${{ env.JASSARI_AUDIENCE }}
          DOCKER_BUILD_ARG_REACT_APP_OIDC_CLIENT_ID: ${{ env.K8S_NAMESPACE }}
          DOCKER_BUILD_ARG_REACT_APP_OIDC_SCOPE: 'openid ${{ env.PROFILE_AUDIENCE }} ${{ env.JASSARI_AUDIENCE }}'
          DOCKER_BUILD_ARG_REACT_APP_JASSARI_FEDERATION_GRAPHQL: 'https://jassari-federation.${{ env.BASE_DOMAIN }}/'
          DOCKER_BUILD_ARG_REACT_APP_SENTRY_DSN: 'https://13e1b97fb11c4d10976a27675061c6c3@sentry.hel.ninja/60'
          DOCKER_BUILD_ARG_REACT_APP_BASE_URL: 'https://jassari-admin.${{ env.BASE_DOMAIN }}/'

  review:
    runs-on: ubuntu-latest
    needs: build
    name: Review
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        env:
          ENVIRONMENT_URL: https://${{ env.K8S_NAMESPACE }}.${{ env.BASE_DOMAIN }}
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-review

      - name: Setup Tunnistamo
        uses: City-of-Helsinki/setup-tunnistamo-action@main
        with:
          kubeconfig_raw: ${{ env.KUBECONFIG_RAW}}
          review_namespace: ${{ env.K8S_NAMESPACE }}
          api_scope: https://api.hel.fi/auth/helsinkiprofile

      - name: Setup Tunnistamo
        uses: City-of-Helsinki/setup-tunnistamo-action@main
        with:
          kubeconfig_raw: ${{ env.KUBECONFIG_RAW}}
          review_namespace: ${{ env.K8S_NAMESPACE }}
          api_scope: https://api.hel.fi/auth/jassariapi
